name: RedEye Programming Language

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Environment Setup
      run: |
        rustup default nightly
        cargo install grcov
        rustup component add llvm-tools-preview

    - name: Run Build
      run: cargo build
    
    - name: Run tests
      run: |
        export RUSTFLAGS="-C instrument-coverage"
        mkdir ./target/debug/coverage
        export LLVM_PROFILE_FILE="./target/debug/coverage/default.profraw"
        cargo test --verbose
    
    - name: Get Coverage Report
      run: |
        grcov . --binary-path ./target/debug/deps -s . -t html --branch --ignore-not-existing -o ./target/debug/coverage/
        
    - name: Copy output files to artifact directory
      run: |
        mkdir artifacts
        for f in ./target/debug/coverage/*
        do
          echo "  Copying $f"
          cp -r -v $f artifacts/
        done
    - name: Upload output files to GitHub so they can be reviewed
      uses: actions/upload-artifact@v1
      with:
        name: coverage_report
        path: artifacts
      
      
